# Site settings
author: Samuel Bennrubi
title: Coding with SB: A Journey for Knowledge
header-img: img/home-bg.png
email: sbennrubi@gmail.com
copyright_name: Samuel Bennrubi
description: > # this means to ignore newlines until "baseurl:"
  Learning and Sharing
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bennrubes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
